name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.4.2
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  # camera: ^0.9.7+1
  camera:
    git: 
      url: 'https://github.com/coral-labs/flutter_plugins.git'
      ref: 'coral'
      path: 'packages/camera/camera'
  path: ^1.8.1
  path_provider: ^2.0.10
  photo_manager: ^2.1.2
  video_player: ^2.4.2

flutter:
  assets:
    - assets/