name: wechat_camera_picker
description: A camera picker which is an extension to wechat_assets_picker, but can be run separately.
version: 2.4.2
homepage: https://github.com/fluttercandies/flutter_wechat_camera_picker
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.0.0'

dependencies:
  flutter:
    sdk: flutter

  camera:
    git: 
      url: 'https://github.com/coral-labs/flutter_plugins.git'
      ref: 'coral'
      path: 'packages/camera/camera'
  path: ^1.8.0
  path_provider: ^2.0.2
  photo_manager: ^1.3.1
  video_player: ^2.1.14

flutter:
  assets:
    - assets/